version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: retroboard
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5433:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: antoine@jaussoin.com
      PGADMIN_DEFAULT_PASSWORD: hello
    restart: unless-stopped

volumes:
  postgres-data:
